export type Status = 'Off-Plan' | 'Ready' | 'Secondary Market'
export type UnitType = 'Studio' | '1BR' | '2BR' | '3BR' | '4BR' | '5BR' | '6BR' | 'Villa' | 'Penthouse' | 'Townhouse'

export interface Property {
  id: string
  developerName: string
  projectName: string
  location: string
  startingPrice: number
  paymentPlan: string
  handoverDate: string | null
  unitTypes: UnitType[]
  goldenVisaEligible: boolean | 'check'
  brochureUrl: string | null
  roiEstimate: number
  status: Status
  image: string
  gallery?: string[]
  videoUrl?: string
  featured: boolean
  description?: string
  amenities?: string[]
  beds?: string
  baths?: string
  sqft?: string
}

export const PROPERTIES: Property[] = [
  {
    id: '1',
    developerName: 'Emaar',
    projectName: 'Mareva 2 — The Oasis',
    location: 'The Oasis, Dubai',
    startingPrice: 3_500_000,
    paymentPlan: '80/20 — 80% during construction, 20% on handover',
    handoverDate: 'Q4 2027',
    unitTypes: ['Villa', 'Townhouse'],
    goldenVisaEligible: true,
    brochureUrl: null,
    roiEstimate: 6.8,
    status: 'Off-Plan',
    image: '/images/properties/mareva2.jpg',
    featured: true,
    beds: '4–6',
    description: 'Mareva 2 is part of Emaar\'s flagship The Oasis master community — a nature-inspired waterfront development featuring lagoons, parks and world-class amenities. Villas and townhouses sit within lush landscaped surroundings with direct water and park frontage.',
    amenities: ['Private pool', 'Lagoon access', 'Running track', 'Retail boulevard', 'Kids\' play areas', 'Clubhouse', 'Gym', 'Parks & green spaces'],
  },
  {
    id: '2',
    developerName: 'Binghatti',
    projectName: 'Binghatti Sky Terraces',
    location: 'Dubai Science Park',
    startingPrice: 850_000,
    paymentPlan: '70/30 — 70% during construction, 30% on handover',
    handoverDate: 'Q3 2027',
    unitTypes: ['1BR', '2BR', '3BR'],
    goldenVisaEligible: false,
    brochureUrl: null,
    roiEstimate: 8.5,
    status: 'Off-Plan',
    image: '/images/properties/sky-terraces.jpg',
    featured: true,
    description: 'Binghatti Sky Terraces is a high-yield residential tower in Dubai Science Park offering spacious apartments with private terraces. Designed for investors seeking strong rental returns from Dubai\'s growing professional tenant base.',
    amenities: ['Infinity pool', 'Gym', 'Private terraces', 'Covered parking', 'Children\'s play area', '24/7 security', 'Lobby lounge'],
  },
  {
    id: '3',
    developerName: 'Binghatti',
    projectName: 'Mercedes-Benz Places | Binghatti City',
    location: 'Nad Al Sheba, Dubai',
    startingPrice: 2_800_000,
    paymentPlan: '60/40 — 60% during construction, 40% on handover',
    handoverDate: 'Q4 2027',
    unitTypes: ['Studio', '1BR', '2BR', '3BR', 'Penthouse'],
    goldenVisaEligible: true,
    brochureUrl: null,
    roiEstimate: 7.2,
    status: 'Off-Plan',
    image: '/images/properties/mercedes-benz-places-hero.jpg',
    gallery: [
      '/images/properties/mercedes-benz-places-hero.jpg',
      '/images/properties/mercedes-benz-places-aerial.jpg',
      '/images/properties/mercedes-benz-places-night.jpg',
      '/images/properties/mercedes-benz-places-pool.jpg',
      '/images/properties/mercedes-benz-places-interior.jpg',
    ],
    featured: true,
    beds: 'Studio – 5BR',
    sqft: 'From 293 sq.ft.',
    description: 'The world\'s first Mercedes-Benz branded city — a masterplanned community of 12 iconic towers in Nad Al Sheba, Dubai. Each tower is named after a legendary Mercedes-Benz concept car, from Project Maybach to Vision AVTR. Co-designed by Mercedes-Benz and Binghatti, every residence carries the precision, performance and prestige of the three-pointed star. 3 minutes from Meydan Racecourse, 8 minutes from Burj Khalifa.',
    amenities: [
      'Sky infinity pool with panoramic views',
      'Private podium pool',
      'Mercedes-Benz concierge service',
      'Valet parking',
      'Spa & wellness centre',
      'State-of-the-art gymnasium',
      'Yoga & outdoor wellness area',
      'Skyline jogging path',
      'Entertainment studios',
      'Grand Promenade — 12 lifestyle experiences',
      'Retail & F&B at podium level',
      'Smart home automation system',
      'Solar photovoltaic technology',
      'LEED certification (aiming)',
      'Acoustic engineering throughout',
      '3 min to Meydan Racecourse · 8 min to Burj Khalifa',
    ],
  },
  {
    id: '4',
    developerName: 'Danube Properties',
    projectName: 'Serenz by Danube',
    location: 'Dubai South',
    startingPrice: 620_000,
    paymentPlan: '1% per month — flexible post-handover plan available',
    handoverDate: 'Q4 2026',
    unitTypes: ['Studio', '1BR', '2BR'],
    goldenVisaEligible: false,
    brochureUrl: null,
    roiEstimate: 8.2,
    status: 'Off-Plan',
    image: '/images/properties/serenz.jpg',
    featured: false,
    description: 'Serenz by Danube is a smartly positioned residential development in Dubai South near Al Maktoum International Airport. Ideal for investors targeting high rental yields from airport zone professionals and Expo City tenants.',
    amenities: ['Swimming pool', 'Gym', 'Retail on ground floor', 'Children\'s play area', 'Covered parking', 'Landscaped gardens'],
  },
  {
    id: '5',
    developerName: 'Sobha Realty',
    projectName: 'Sobha Central',
    location: 'Sheikh Zayed Road, Dubai',
    startingPrice: 1_520_000,
    paymentPlan: '60/40 — 60% during construction, 40% on completion',
    handoverDate: 'December 2029',
    unitTypes: ['1BR', '2BR'],
    goldenVisaEligible: true,
    brochureUrl: null,
    roiEstimate: 7.0,
    status: 'Off-Plan',
    image: '/images/properties/sobha-central-balcony.jpg',
    gallery: [
      '/images/properties/sobha-central-balcony.jpg',
      '/images/properties/sobha-central-aerial.jpg',
      '/images/properties/sobha-central-pool.jpg',
      '/images/properties/sobha-central-towers.jpg',
      '/images/properties/sobha-central-bedroom.jpg',
    ],
    videoUrl: 'https://www.youtube.com/embed/Z2248o9lyv0',
    featured: true,
    beds: '1 & 2',
    sqft: '568 – 1,554 sq.ft.',
    description: 'Sobha Central rises across 6 interconnected towers (G+60 to G+94) on Sheikh Zayed Road — Dubai\'s most iconic address. With ~1,225 residences offering panoramic views of Palm Jumeirah, Dubai Eye and the Arabian Gulf, this is Sobha Realty\'s most centrally located masterplan. 2BR units from AED 2.48M qualify for the UAE 10-Year Golden Visa.',
    amenities: ['Resort-style pool with fountains', 'Panoramic views — Palm, Dubai Eye & Gulf', 'World-class fitness centre', 'Rooftop sky lounges', 'Retail promenade', 'Business centre', 'Children\'s play area', 'EV charging stations', 'Concierge & valet service', 'Walking distance to metro', 'Community mall', 'Direct Sheikh Zayed Road access'],
  },
  {
    id: '6',
    developerName: 'Ellington Properties',
    projectName: 'Windsor House',
    location: 'Business Bay, Dubai',
    startingPrice: 1_950_000,
    paymentPlan: '50/50 — Equal split during construction',
    handoverDate: 'Q3 2027',
    unitTypes: ['1BR', '2BR', '3BR'],
    goldenVisaEligible: true,
    brochureUrl: null,
    roiEstimate: 7.4,
    status: 'Off-Plan',
    image: '/images/properties/windsor-house.jpg',
    featured: false,
    description: 'Windsor House by Ellington Properties brings the developer\'s signature design-led approach to Business Bay. Premium apartments with hotel-grade lobby, wellness amenities and Ellington\'s award-winning interior finishes — consistently achieving 15–25% higher rental rates than neighbouring buildings.',
    amenities: ['Resort-style pool', 'Fitness studio', 'Yoga deck', 'Business lounge', 'Concierge service', 'Landscaped podium', 'Children\'s play area', 'EV charging'],
  },
  {
    id: '7',
    developerName: 'Imtiaz Developments',
    projectName: 'Beach Walk Residence 4',
    location: 'Dubai Islands',
    startingPrice: 1_200_000,
    paymentPlan: '60/40 — 60% during construction, 40% on handover',
    handoverDate: 'Q2 2027',
    unitTypes: ['Studio', '1BR', '2BR'],
    goldenVisaEligible: false,
    brochureUrl: null,
    roiEstimate: 8.0,
    status: 'Off-Plan',
    image: '/images/properties/beach-walk.jpg',
    featured: true,
    description: 'Beach Walk Residence 4 is Imtiaz Developments\' latest waterfront offering on Dubai Islands — Dubai\'s exciting new coastal master community. Steps from the beach with strong projected rental demand from tourists and short-term rental investors.',
    amenities: ['Beach access', 'Infinity pool', 'Gym', 'Retail & dining on podium', 'Covered parking', 'Rooftop terrace', 'Smart home features'],
  },
  {
    id: '8',
    developerName: 'Imtiaz Developments',
    projectName: 'Pearl House 4',
    location: 'Jumeirah Garden City',
    startingPrice: 980_000,
    paymentPlan: '60/40 — 60% during construction, 40% on handover',
    handoverDate: 'Q4 2027',
    unitTypes: ['Studio', '1BR', '2BR'],
    goldenVisaEligible: false,
    brochureUrl: null,
    roiEstimate: 7.9,
    status: 'Off-Plan',
    image: '/images/properties/pearl-house.jpg',
    featured: false,
    description: 'Pearl House 4 is located in Jumeirah Garden City, one of Dubai\'s fastest-growing mid-market residential corridors between Sheikh Zayed Road and Al Wasl Road. A strong buy-to-let option targeting professionals seeking proximity to Business Bay and DIFC.',
    amenities: ['Swimming pool', 'Gym', 'Landscaped gardens', 'Children\'s play area', 'Covered parking', '24/7 security', 'Retail ground floor'],
  },
  {
    id: '9',
    developerName: 'Imtiaz Developments',
    projectName: 'Wynwood Horizon',
    location: 'Al Furjan, Dubai',
    startingPrice: 750_000,
    paymentPlan: '70/30 — 70% during construction, 30% on handover',
    handoverDate: 'Q1 2028',
    unitTypes: ['Studio', '1BR', '2BR'],
    goldenVisaEligible: false,
    brochureUrl: null,
    roiEstimate: 8.3,
    status: 'Off-Plan',
    image: '/images/properties/wynwood.jpg',
    featured: false,
    description: 'Wynwood Horizon brings a creative, lifestyle-forward aesthetic to Al Furjan — a well-connected community with metro access and strong rental demand. High gross yields make this an attractive entry-level investment property.',
    amenities: ['Rooftop pool', 'Co-working lounge', 'Gym', 'Padel court', 'EV charging', 'Smart home tech', 'Concierge', 'Metro-connected'],
  },
  {
    id: '11',
    developerName: 'Sobha Realty',
    projectName: 'Sobha Elwood',
    location: 'Dubailand, Dubai-Al Ain Road',
    startingPrice: 7_930_000,
    paymentPlan: '60/40 — 60% during construction, 40% on completion',
    handoverDate: 'Q4 2027',
    unitTypes: ['4BR', '5BR', '6BR', 'Villa'],
    goldenVisaEligible: true,
    brochureUrl: null,
    roiEstimate: 6.2,
    status: 'Off-Plan',
    image: '/images/properties/sobha-elwood-street.jpg',
    gallery: [
      '/images/properties/sobha-elwood-street.jpg',
      '/images/properties/sobha-elwood-pool.jpg',
      '/images/properties/sobha-elwood-front.jpg',
      '/images/properties/sobha-elwood-pool2.jpg',
      '/images/properties/sobha-elwood-front2.jpg',
    ],
    featured: true,
    beds: '4, 5 & 6',
    sqft: 'From 5,500 sq.ft.',
    description: 'Sobha Elwood is an exclusive urban living retreat positioned along the Dubai-Al Ain Road, nestled amidst 10,000+ trees inspired by the world\'s 7 greatest forests. Spanning 10 million sq.ft., the community offers standalone villas with no shared walls, private swimming pools, and 47% open space. Designed for families seeking privacy, nature, and the highest build quality.',
    amenities: [
      'Private swimming pool (every villa)',
      'No shared walls',
      '10,000+ trees across the community',
      '7 forest-themed parks',
      'Lap pool & water features',
      'Padel / pickleball tennis',
      'Cricket pitch',
      'Yoga lawn',
      'Skate park',
      'Dog park with agility equipment',
      'Baobab tree court',
      'Botanical & fragrant gardens',
      'Running & jogging track',
      'Outdoor fitness area',
      'Kids\' forest play areas',
      'Treehouse',
      'Clubhouse',
      'EV charging & micromobility infrastructure',
      'Home automation features',
      'Bosch/Siemens kitchen appliances',
      'Duravit & Grohe bathrooms',
      'Marble flooring in living areas',
    ],
  },
  {
    id: '12',
    developerName: 'Sobha Realty',
    projectName: 'Sobha SkyParks',
    location: 'Sheikh Zayed Road, Business Bay, Dubai',
    startingPrice: 2_860_000,
    paymentPlan: '70/30 — 10% booking, 60% during construction, 30% on handover',
    handoverDate: 'December 2031',
    unitTypes: ['1BR', '2BR', '3BR', '4BR', 'Penthouse'],
    goldenVisaEligible: true,
    brochureUrl: null,
    roiEstimate: 8.0,
    status: 'Off-Plan',
    image: '/images/properties/sobha-skyparks-lounge.jpg',
    gallery: [
      '/images/properties/sobha-skyparks-lounge.jpg',
      '/images/properties/sobha-skyparks-pool.jpg',
      '/images/properties/sobha-skyparks-terrace.jpg',
      '/images/properties/sobha-skyparks-hero.jpg',
      '/images/properties/sobha-skyparks-garden.jpg',
    ],
    featured: true,
    beds: '1–4 + Duplex',
    sqft: '684 – 4,956 sq.ft.',
    description: 'Rising 450 metres above Sheikh Zayed Road, Sobha SkyParks is Dubai\'s most anticipated supertall residential landmark — 109 floors, 684 residences, and 4 immersive Sky-Parks spanning 24 levels. Located between Downtown Dubai and Business Bay with direct metro access. 1BR from AED 2.86M, 2BR from AED 4.75M, 3BR from AED 9.35M. Floor-to-ceiling glass throughout, sweeping views of the Burj Khalifa, Arabian Gulf and Dubai skyline from every level. Completion December 2031.',
    amenities: [
      'Infinity pool at 370m — Burj Khalifa & Gulf views',
      'Zone 1 Adventure SkyPark — kids splash, slides, padel, gaming',
      'Zone 2 Active Life SkyPark — skyline running track, yoga, calisthenics',
      'Zone 3 Lush Life SkyPark — zen gardens, glass pavilions, sensory path',
      'Zone 4 Luxe Life SkyPark — floating deck, private terraces, sunset dining',
      'Grand hotel-style lobby',
      'Floor-to-ceiling windows in all residences',
      'Private balconies — SZR, Gulf, Downtown & Canal views',
      'Fully fitted Bosch kitchen (fridge, oven, hob, dishwasher, washer-dryer)',
      'Duravit sanitary fixtures',
      'Smart home automation (temperature & lighting)',
      'High-performance double-glazed facade',
      '5 min to Business Bay · 10 min to DIFC · 13 min to Downtown',
      'Business Bay Metro Station — walking distance',
      'All units above AED 2M eligible for UAE 10-Year Golden Visa',
      'Projected 8–9% rental yield',
      '4–6% annual price appreciation forecast',
    ],
  },  {
    id: '13',
    developerName: 'Sobha Realty',
    projectName: 'Sobha Sanctuary',
    location: 'Dubailand, Al Ain Road, Dubai',
    startingPrice: 3_990_000,
    paymentPlan: '10/50/40 — 10% booking, 50% during construction, 40% on handover',
    handoverDate: 'Q3 2029',
    unitTypes: ['4BR', '5BR', '6BR', 'Villa', 'Townhouse'],
    goldenVisaEligible: true,
    brochureUrl: null,
    roiEstimate: 6.5,
    status: 'Off-Plan' as const,
    image: '/images/properties/sobha-sanctuary-hero.jpg',
    gallery: [
      '/images/properties/sobha-sanctuary-hero.jpg',
      '/images/properties/sobha-sanctuary-lagoon.jpg',
      '/images/properties/sobha-sanctuary-waterfall.jpg',
      '/images/properties/sobha-sanctuary-bedroom.jpg',
      '/images/properties/sobha-sanctuary-mall.jpg',
    ],
    videoUrl: 'https://www.youtube.com/embed/qalr65QxbI0',
    featured: true,
    beds: '4, 5 & 6',
    sqft: '2,459 – 7,191 sq.ft.',
    description: "Sobha Sanctuary is Sobha Realty's most ambitious masterplan — a AED 50 billion, 37.4 million sq.ft. wellness community in Dubailand designed for 20,000 families. Built around 6km of crystal lagoons, 50,000+ trees, and a 1 million sq.ft. central park, it features its own mall, two international schools, a hospital, and 22km of cycling tracks.",
    amenities: [
      '6km Crystal Lagoon with beach access',
      'Sobha Sanctuary Mall — retail & dining',
      'Two international schools on-site',
      'Community hospital',
      '1 million sq.ft. Central Park',
      '22km cycling tracks',
      '9km jogging & wellness loop',
      '50,000+ trees across the masterplan',
      'Padel courts & football grounds',
      'Skate park',
      'Yoga pavilions & meditation gardens',
      'State-of-the-art wellness centre',
      'Private boat rides & water plaza',
      'Resort-style swimming pools',
      'Pet-friendly walking routes',
    ],
  },
  ,{
    id: '14',
    developerName: 'Danube Properties',
    projectName: 'Greenz by Danube',
    location: 'Dubai Academic City, near Dubai Silicon Oasis',
    startingPrice: 2_500_000,
    paymentPlan: '1% monthly payment plan',
    handoverDate: 'December 2029',
    unitTypes: ['3BR', '4BR', '5BR', 'Townhouse', 'Villa'],
    goldenVisaEligible: true,
    brochureUrl: null,
    roiEstimate: 7.5,
    status: 'Off-Plan' as const,
    image: '/images/properties/greenz-front.jpg',
    gallery: [
      '/images/properties/greenz-front.jpg',
      '/images/properties/greenz-beachhub.jpg',
      '/images/properties/greenz-spa.jpg',
      '/images/properties/greenz-sanctuary.jpg',
      '/images/properties/greenz-wellness.jpg',
    ],
    videoUrl: 'https://www.youtube.com/embed/u7dexMTtfFY',
    featured: true,
    beds: '3, 4 & 5',
    sqft: 'Townhouses from ~2,500 sq.ft. | Twin Villas from ~4,000 sq.ft.',
    description: "Greenz by Danube is a master-planned resort community in Dubai Academic City — townhouses and twin villas surrounded by lush greenery, a musical dancing fountain, and 50+ world-class amenities across 20,000 sq.ft. of lifestyle space. Backed by Dubai's AED 12.8 billion Silicon Oasis tech-hub expansion (District 10 initiative), Greenz sits within one of Dubai's fastest-growing corridors — 5 min from Sheikh Mohammed bin Zayed Road, 18 min from Downtown Dubai. Fully furnished by Dolce Vita with Italian kitchen appliances, private elevators, floating staircases, and private sky gardens.",
    amenities: [
      'Musical Dancing Fountain — heart of the community',
      '3.75km circular jogging & cycling track',
      'Beach lagoon with sandy beach club & rooftop terrace',
      'Resort-style swimming pools & kids water park',
      '20,000 sq.ft. fitness & wellness centre',
      '2-floor panoramic gym with natural light',
      'Spa — steam, sauna, ice bath, infrared & cryotherapy',
      '10 dedicated sports courts (tennis, padel, football, cricket, basketball)',
      'Kids nursery, play zones, trampoline & wall climbing',
      'Indoor cinema, podcast room & business centre',
      'Family BBQ area & cabana seating',
      'Open yoga, meditation & Zumba platforms',
      'Giant musical piano walkway',
      'Mosque at community centre',
      '20,000 sq.ft. retail & dining promenade',
      'Electric golf cart transit & metro shuttle every 30 min',
      'Fully furnished by Dolce Vita (villas & townhouses)',
      'Private elevator inside every 4BR & 5BR home',
      'Private sky garden on roof floor',
      'Italian kitchen appliances & floating staircase',
      'Golden Visa eligible (all units above AED 2M)',
      '27 international universities within 5 minutes',
      '4-6% annual price appreciation forecast',
    ],
  },
]

export const STATUS_COLORS: Record<Status, string> = {
  'Off-Plan': 'bg-blue-100 text-blue-800',
  'Ready': 'bg-green-100 text-green-800',
  'Secondary Market': 'bg-amber-100 text-amber-800',
}

export const AED_RATE: Record<string, number> = {
  AED: 1,
  INR: 22.8,
  USD: 0.272,
  GBP: 0.215,
  EUR: 0.251,
  SGD: 0.367,
}
