export type Status = 'Off-Plan' | 'Ready' | 'Secondary Market'
export type UnitType = 'Studio' | '1BR' | '2BR' | '3BR' | '4BR' | '5BR' | '6BR' | 'Villa' | 'Penthouse' | 'Townhouse'

export interface Property {
  id: string
  developerName: string
  projectName: string
  location: string
  startingPrice: number
  paymentPlan: string
  handoverDate: string | null
  unitTypes: UnitType[]
  goldenVisaEligible: boolean | 'check'
  brochureUrl: string | null
  roiEstimate: number
  status: Status
  image: string
  gallery?: string[]
  videoUrl?: string
  featured: boolean
  description?: string
  amenities?: string[]
  beds?: string
  baths?: string
  sqft?: string
}

export const PROPERTIES: Property[] = [
  {
    id: '1',
    developerName: 'Emaar',
    projectName: 'Mareva 2 — The Oasis',
    location: 'The Oasis, Dubai',
    startingPrice: 3_500_000,
    paymentPlan: '80/20 — 80% during construction, 20% on handover',
    handoverDate: 'Q4 2027',
    unitTypes: ['Villa', 'Townhouse'],
    goldenVisaEligible: true,
    brochureUrl: null,
    roiEstimate: 6.8,
    status: 'Off-Plan',
    image: '/images/properties/mareva2.jpg',
    featured: true,
    beds: '4–6',
    description: 'Mareva 2 is part of Emaar\'s flagship The Oasis master community — a nature-inspired waterfront development featuring lagoons, parks and world-class amenities. Villas and townhouses sit within lush landscaped surroundings with direct water and park frontage.',
    amenities: ['Private pool', 'Lagoon access', 'Running track', 'Retail boulevard', 'Kids\' play areas', 'Clubhouse', 'Gym', 'Parks & green spaces'],
  },
  {
    id: '2',
    developerName: 'Binghatti',
    projectName: 'Binghatti Sky Terraces',
    location: 'Motor City, Dubai',
    startingPrice: 850_000,
    paymentPlan: '70/30 — 70% during construction, 30% on handover',
    handoverDate: 'Q3 2027',
    unitTypes: ['Studio', '1BR', '2BR', '3BR'],
    goldenVisaEligible: 'check',
    brochureUrl: null,
    roiEstimate: 8.5,
    status: 'Off-Plan',
    image: '/images/properties/binghatti-skyterraces-hero.jpg',
    gallery: [
      '/images/properties/binghatti-skyterraces-hero.jpg',
      '/images/properties/binghatti-skyterraces-night.jpg',
      '/images/properties/binghatti-skyterraces-pool.jpg',
      '/images/properties/binghatti-skyterraces-amenities.jpg',
      '/images/properties/binghatti-skyterraces-park.jpg',
    ],
    featured: true,
    beds: 'Studio – 3BR',
    sqft: 'From 307 sq.ft.',
    description: 'Binghatti Sky Terraces rises across 2B + G + 6P + 40 residential floors in Motor City — one of Dubai\'s most consistently top-ranked family communities for quality of life. A landmark twin-tower development of 1,840 residences with signature deep sky terraces on every floor, maximising light and panoramic views. 5 minutes from Dubai Autodrome, 8 minutes from Miracle Garden, 20 minutes from Burj Khalifa. Designed for both end-users and investors seeking strong rental yields from Dubai\'s growing professional and family tenant base.',
    amenities: [
      'Adult pool & shallow water pool',
      'Kids pool & water splash game',
      'Kids play area',
      'Family sitting zone',
      'Padel court',
      'Green sky terraces on every floor',
      'Indoor gym',
      'Jogging track',
      'Yoga area',
      'Retail at ground level (26 units)',
      '5 min to Dubai Autodrome',
      '8 min to Miracle & Butterfly Garden',
      '12 min to Global Village',
      '18 min to Dubai International Airport',
      '20 min to Burj Khalifa & Dubai Mall',
    ],
  },
  {
    id: '10',
    developerName: 'Binghatti',
    projectName: 'Binghatti Wraith',
    location: 'Al Jaddaf, Dubai',
    startingPrice: 1_100_000,
    paymentPlan: '70/30 — 70% during construction, 30% on handover',
    handoverDate: 'Q4 2027',
    unitTypes: ['Studio', '1BR', '2BR', '3BR'],
    goldenVisaEligible: 'check',
    brochureUrl: null,
    roiEstimate: 8.5,
    status: 'Off-Plan',
    image: '/images/properties/binghatti-wraith-bird.jpg',
    gallery: [
      '/images/properties/binghatti-wraith-bird.jpg',
      '/images/properties/binghatti-wraith-aerial.jpg',
      '/images/properties/binghatti-wraith-amenities2.jpg',
      '/images/properties/binghatti-wraith-amenities1.jpg',
      '/images/properties/binghatti-wraith-street.jpg',
    ],
    featured: true,
    beds: 'Studio – 3BR',
    sqft: 'Studios from 341 sq.ft.',
    description: 'Binghatti Wraith rises as a 19-storey architectural landmark in the heart of Al Jaddaf — a historically rich, rapidly evolving community positioned between Dubai Creek and the Business Bay Extension. Its distinctive curved facade and signature geometric exterior create 360-degree unobstructed views from within a major roundabout, ensuring the tower can never be boxed in or hidden by future construction. 855 residences across Studio, 1BR, 2BR and 3BR apartments. 2 minutes from Al Jaddaf Metro Station (Green Line). 10–12 minutes from Downtown Dubai & Burj Khalifa. 26+ resort-style amenities including infinity pool, padel court, outdoor yoga deck and family BBQ zone. Designed for professionals, families and vacation rental investors.',
    amenities: [
      'Infinity pool — temperature-controlled with horizon views',
      'Jacuzzi & shallow pool',
      'Sun deck, loungers & private cabanas',
      'Pool bar',
      'Gym & fitness centre with premium equipment',
      'Outdoor fitness area & yoga deck',
      'Padel court & half-basketball court',
      'Scenic walking track around perimeter',
      'Kids pool & aqua play area',
      'Children\'s outdoor playground',
      'Family BBQ area',
      'Double-height lobby — 24/7 concierge',
      '34 ground-floor retail spaces',
      '4 podium floors: covered parking & amenity deck',
      'Crystalline glass facade with integrated LED accent lighting',
      'Floor-to-ceiling windows & continuous balconies',
      '2 min — Al Jaddaf Metro Station (Green Line)',
      '2 min — Dubai Design District (d3) & Al Jaddaf Walk',
      '10–12 min — Downtown Dubai & Burj Khalifa',
      '10–12 min — Museum of the Future, Dubai Opera, Meydan',
      'Less than 1km — Jaddaf Waterfront',
      '90-second access to Al Khail Road, Sheikh Zayed Road & Oud Metha Road',
    ],
  },
  {
    id: '3',
    developerName: 'Binghatti',
    projectName: 'Mercedes-Benz Places | Binghatti City',
    location: 'Nad Al Sheba, Dubai',
    startingPrice: 2_800_000,
    paymentPlan: '60/40 — 60% during construction, 40% on handover',
    handoverDate: 'Q4 2027',
    unitTypes: ['Studio', '1BR', '2BR', '3BR', 'Penthouse'],
    goldenVisaEligible: true,
    brochureUrl: null,
    roiEstimate: 7.2,
    status: 'Off-Plan',
    image: '/images/properties/mercedes-benz-places-hero.jpg',
    gallery: [
      '/images/properties/mercedes-benz-places-hero.jpg',
      '/images/properties/mercedes-benz-places-aerial.jpg',
      '/images/properties/mercedes-benz-places-night.jpg',
      '/images/properties/mercedes-benz-places-pool.jpg',
      '/images/properties/mercedes-benz-places-interior.jpg',
    ],
    featured: true,
    beds: 'Studio – 5BR',
    sqft: 'From 293 sq.ft.',
    description: 'The world\'s first Mercedes-Benz branded city — a masterplanned community of 12 iconic towers in Nad Al Sheba, Dubai. Each tower is named after a legendary Mercedes-Benz concept car, from Project Maybach to Vision AVTR. Co-designed by Mercedes-Benz and Binghatti, every residence carries the precision, performance and prestige of the three-pointed star. 3 minutes from Meydan Racecourse, 8 minutes from Burj Khalifa.',
    amenities: [
      'Sky infinity pool with panoramic views',
      'Private podium pool',
      'Mercedes-Benz concierge service',
      'Valet parking',
      'Spa & wellness centre',
      'State-of-the-art gymnasium',
      'Yoga & outdoor wellness area',
      'Skyline jogging path',
      'Entertainment studios',
      'Grand Promenade — 12 lifestyle experiences',
      'Retail & F&B at podium level',
      'Smart home automation system',
      'Solar photovoltaic technology',
      'LEED certification (aiming)',
      'Acoustic engineering throughout',
      '3 min to Meydan Racecourse · 8 min to Burj Khalifa',
    ],
  },
  {
    id: '4',
    developerName: 'Danube Properties',
    projectName: 'Serenz by Danube',
    location: 'Jumeirah Village Circle (JVC), Dubai',
    startingPrice: 620_000,
    paymentPlan: '1% per month — flexible post-handover plan',
    handoverDate: 'Q4 2026',
    unitTypes: ['Studio', '1BR', '2BR', '3BR'],
    goldenVisaEligible: false,
    brochureUrl: null,
    roiEstimate: 8.5,
    status: 'Off-Plan',
    image: '/images/properties/serenz-pool.jpg',
    gallery: [
      '/images/properties/serenz-pool.jpg',
      '/images/properties/serenz-night.jpg',
      '/images/properties/serenz-exterior.jpg',
      '/images/properties/serenz-interior.jpg',
      '/images/properties/serenz-amenities.jpg',
    ],
    videoUrl: 'https://www.youtube.com/embed/UVDJ57O5s8U',
    featured: false,
    beds: 'Studio – 3BR',
    sqft: 'From 383 sq.ft.',
    description: "Serenz by Danube is a striking 50-storey residential landmark in the heart of Jumeirah Village Circle — Dubai's most sought-after community for investors. Conceptualised as 'A World of Amenities', it delivers 40+ curated lifestyle experiences across 120,000 sq.ft. of premium lifestyle spaces. Entry and exit in 2 minutes via Al Khail Road & Sheikh Mohammed Bin Zayed Road. Fully furnished residences where Modern Minimalism meets Luxury. Proposed metro station nearby seals the investment case.",
    amenities: [
      'Serenity Pool — infinity pool with floating island seating',
      'Aqua Park — kids water park & splash pad',
      'Serenity Spa — steam, sauna & rejuvenation suites',
      'Serenity Garden & Serenity Fountain',
      'Indoor Gym & Aquatic Gym',
      'Outdoor Calisthenics Park',
      'Football Court, Padel, Pickleball, Badminton, Cricket & Basketball',
      'Snookball court',
      'Kids Adventureland, Trampoline & Wall Climbing',
      'Kids Day Care & Kids Cycling Track',
      'Hammock Garden, Meditation Zone & Outdoor Yoga',
      'Family Cabana Seating & BBQ Deck',
      'Business Centre & Clubhouse',
      'Male & Female Steam and Sauna',
      'Male & Female Prayer Halls',
      'Sensory Park & Urban Park',
      'Drone Docking Zone',
      'Fully furnished premium residences',
      '2 min to Al Khail Road & Sheikh Zayed Road',
      '7 min to Circle Mall · 14 min to Mall of Emirates · 16 min to Dubai Marina',
    ],
  },
  {
    id: '5',
    developerName: 'Sobha Realty',
    projectName: 'Sobha Central',
    location: 'Sheikh Zayed Road, Dubai',
    startingPrice: 1_520_000,
    paymentPlan: '60/40 — 60% during construction, 40% on completion',
    handoverDate: 'December 2029',
    unitTypes: ['1BR', '2BR'],
    goldenVisaEligible: true,
    brochureUrl: null,
    roiEstimate: 7.0,
    status: 'Off-Plan',
    image: '/images/properties/sobha-central-balcony.jpg',
    gallery: [
      '/images/properties/sobha-central-balcony.jpg',
      '/images/properties/sobha-central-aerial.jpg',
      '/images/properties/sobha-central-pool.jpg',
      '/images/properties/sobha-central-towers.jpg',
      '/images/properties/sobha-central-bedroom.jpg',
    ],
    videoUrl: 'https://www.youtube.com/embed/Z2248o9lyv0',
    featured: true,
    beds: '1 & 2',
    sqft: '568 – 1,554 sq.ft.',
    description: 'Sobha Central rises across 6 interconnected towers (G+60 to G+94) on Sheikh Zayed Road — Dubai\'s most iconic address. With ~1,225 residences offering panoramic views of Palm Jumeirah, Dubai Eye and the Arabian Gulf, this is Sobha Realty\'s most centrally located masterplan. 2BR units from AED 2.48M qualify for the UAE 10-Year Golden Visa.',
    amenities: ['Resort-style pool with fountains', 'Panoramic views — Palm, Dubai Eye & Gulf', 'World-class fitness centre', 'Rooftop sky lounges', 'Retail promenade', 'Business centre', 'Children\'s play area', 'EV charging stations', 'Concierge & valet service', 'Walking distance to metro', 'Community mall', 'Direct Sheikh Zayed Road access'],
  },
  {
    id: '6',
    developerName: 'Ellington Properties',
    projectName: 'Windsor House',
    location: 'Business Bay, Dubai',
    startingPrice: 1_950_000,
    paymentPlan: '50/50 — Equal split during construction',
    handoverDate: 'Q3 2027',
    unitTypes: ['1BR', '2BR', '3BR'],
    goldenVisaEligible: true,
    brochureUrl: null,
    roiEstimate: 7.4,
    status: 'Off-Plan',
    image: '/images/properties/windsor-house.jpg',
    featured: false,
    description: 'Windsor House by Ellington Properties brings the developer\'s signature design-led approach to Business Bay. Premium apartments with hotel-grade lobby, wellness amenities and Ellington\'s award-winning interior finishes — consistently achieving 15–25% higher rental rates than neighbouring buildings.',
    amenities: ['Resort-style pool', 'Fitness studio', 'Yoga deck', 'Business lounge', 'Concierge service', 'Landscaped podium', 'Children\'s play area', 'EV charging'],
  },
  {
    id: '7',
    developerName: 'Imtiaz Developments',
    projectName: 'Beach Walk Residence 4',
    location: 'Dubai Islands',
    startingPrice: 1_200_000,
    paymentPlan: '60/40 — 20% booking · 5% Aug 2025 · 5% Nov 2025 · 10% Mar 2026 · 5% Jun 2026 · 10% Oct 2026 · 5% Mar 2027 · 40% on completion (June 2027)',
    handoverDate: 'June 2027',
    unitTypes: ['1BR', '2BR', '3BR'],
    goldenVisaEligible: 'check',
    brochureUrl: null,
    roiEstimate: 8.0,
    status: 'Off-Plan',
    image: '/images/properties/beach-walk-4-hero.jpg',
    gallery: [
      '/images/properties/beach-walk-4-hero.jpg',
      '/images/properties/beach-walk-4-rooftop-pool.jpg',
      '/images/properties/beach-walk-4-balconies.jpg',
      '/images/properties/beach-walk-4-lobby.jpg',
      '/images/properties/beach-walk-4-bedroom.jpg',
    ],
    featured: true,
    beds: '1, 2 & 3BR',
    sqft: '1BR from 776 sq.ft · 2BR from 1,305 sq.ft · 3BR from 1,790 sq.ft · Duplex from 2,522 sq.ft',
    description: 'Beach Walk Residence 4 by Imtiaz Developments sits on Dubai Islands — an iconic coastal master community with 9 marinas, 2 golf courses, 86 resorts & hotels and 21km of pristine beachfront. Just 5 minutes from Infinity Bridge and 12 minutes from Dubai International Airport, the project delivers waterfront residences — 1BR, 2BR, 3BR and 3BR Duplex — with sweeping ocean views from every unit. Designed as an icon of coastal elegance with a grand curved facade, rooftop infinity pool and lush landscaped podium. A perfect blend of luxury lifestyle and strong rental investment potential in one of Dubai\'s most exciting growth corridors.',
    amenities: [
      'Rooftop infinity pool with panoramic ocean views',
      'Family swimming pool',
      'Fully equipped gym',
      'Outdoor yoga retreat',
      'Zen garden',
      'Rooftop garden',
      'BBQ area',
      'Club room',
      'Kids play area',
      'Grand entrance lobby',
      'Extra visitor parking',
      'Dubai Islands — 9 marinas & 2 golf courses',
      '21km of pristine beachfront',
      '86 resorts & hotels in the community',
      '5 min — Infinity Bridge & Waterfront Market',
      '8 min — Al Mamzar Beach & nearest metro',
      '12 min — Dubai International Airport',
      '15 min — La Mer Beach & Cruise Terminal',
      '24 min — Downtown Dubai & Dubai Mall',
    ],
  },
  {
    id: '8',
    developerName: 'Imtiaz Developments',
    projectName: 'Pearl House 4',
    location: 'Jumeirah Garden City',
    startingPrice: 980_000,
    paymentPlan: '60/40 — 60% during construction, 40% on handover',
    handoverDate: 'Q4 2027',
    unitTypes: ['Studio', '1BR', '2BR'],
    goldenVisaEligible: false,
    brochureUrl: null,
    roiEstimate: 7.9,
    status: 'Off-Plan',
    image: '/images/properties/pearl-house.jpg',
    featured: false,
    description: 'Pearl House 4 is located in Jumeirah Garden City, one of Dubai\'s fastest-growing mid-market residential corridors between Sheikh Zayed Road and Al Wasl Road. A strong buy-to-let option targeting professionals seeking proximity to Business Bay and DIFC.',
    amenities: ['Swimming pool', 'Gym', 'Landscaped gardens', 'Children\'s play area', 'Covered parking', '24/7 security', 'Retail ground floor'],
  },
  {
    id: '9',
    developerName: 'Mira Developments',
    projectName: 'John Richmond District',
    location: 'Al Furjan, Dubai',
    startingPrice: 913_000,
    paymentPlan: '45/5/50 — 10% booking · 10% after 30 days · 5% every 6 months during construction · 5% on completion · 5% at 3 & 6 months post-handover · then 4% quarterly for 3 years (full post-handover plan included)',
    handoverDate: 'Q1 2028',
    unitTypes: ['Studio', '1BR', '2BR'],
    goldenVisaEligible: 'check',
    brochureUrl: null,
    roiEstimate: 8.5,
    status: 'Off-Plan',
    image: '/images/properties/richmond-hero.jpg',
    gallery: [
      '/images/properties/richmond-hero.jpg',
      '/images/properties/richmond-pool.jpg',
      '/images/properties/richmond-walkways.jpg',
      '/images/properties/richmond-community.jpg',
      '/images/properties/richmond-interior.jpg',
    ],
    featured: true,
    beds: 'Studio – 2BR',
    sqft: 'Studio from 420 sq.ft · 1BR from 802 sq.ft · 2BR from 1,322 sq.ft',
    description: 'John Richmond District by Mira Developments is Al Furjan\'s first fully integrated master plan — five residential towers and one office tower united by a shared podium of retail, wellness and leisure. Designed by architect Marco Casamonti in collaboration with iconic British fashion house John Richmond, the project\'s distinctive modern mashrabiya facades blend Islamic heritage with couture luxury. Fully furnished by John Richmond with tailored lines and bold detailing. Located steps from Discovery Gardens Metro Station with 5-star hotel-level services: valet parking, concierge, butler, room service and housekeeping. Studios from AED 913K with a 3-year post-handover payment plan. Backed by Mira Care — the UAE\'s first 5-year maintenance warranty.',
    amenities: [
      'Three resort-style community pools',
      'Decorative waterfall & aesthetic water bodies',
      'Landscaped walkways between towers',
      'State-of-the-art Technogym gym',
      'Outdoor fitness area',
      'Yoga zone',
      'Padel court',
      'Table tennis area',
      'Luxury spa with treatment rooms',
      'Cafés and restaurants on podium',
      'Retail outlets on podium',
      'Fully furnished by John Richmond',
      'Modern Mashrabiya screens — operable, dynamic facade',
      '5-star hotel services: valet parking, concierge, butler, room service',
      'Housekeeping service',
      'Mira Care — 5-year maintenance warranty',
      '0 min — Discovery Gardens Metro Station',
      '8 min — Bluewaters Island',
      '10 min — Palm Jumeirah',
      '18 min — Downtown Dubai & Dubai Mall',
      '20 min — Al Maktoum International Airport',
    ],
  },
  {
    id: '11',
    developerName: 'Sobha Realty',
    projectName: 'Sobha Elwood',
    location: 'Dubailand, Dubai-Al Ain Road',
    startingPrice: 7_930_000,
    paymentPlan: '60/40 — 60% during construction, 40% on completion',
    handoverDate: 'Q4 2027',
    unitTypes: ['4BR', '5BR', '6BR', 'Villa'],
    goldenVisaEligible: true,
    brochureUrl: null,
    roiEstimate: 6.2,
    status: 'Off-Plan',
    image: '/images/properties/sobha-elwood-street.jpg',
    gallery: [
      '/images/properties/sobha-elwood-street.jpg',
      '/images/properties/sobha-elwood-pool.jpg',
      '/images/properties/sobha-elwood-front.jpg',
      '/images/properties/sobha-elwood-pool2.jpg',
      '/images/properties/sobha-elwood-front2.jpg',
    ],
    featured: true,
    beds: '4, 5 & 6',
    sqft: 'From 5,500 sq.ft.',
    description: 'Sobha Elwood is an exclusive urban living retreat positioned along the Dubai-Al Ain Road, nestled amidst 10,000+ trees inspired by the world\'s 7 greatest forests. Spanning 10 million sq.ft., the community offers standalone villas with no shared walls, private swimming pools, and 47% open space. Designed for families seeking privacy, nature, and the highest build quality.',
    amenities: [
      'Private swimming pool (every villa)',
      'No shared walls',
      '10,000+ trees across the community',
      '7 forest-themed parks',
      'Lap pool & water features',
      'Padel / pickleball tennis',
      'Cricket pitch',
      'Yoga lawn',
      'Skate park',
      'Dog park with agility equipment',
      'Baobab tree court',
      'Botanical & fragrant gardens',
      'Running & jogging track',
      'Outdoor fitness area',
      'Kids\' forest play areas',
      'Treehouse',
      'Clubhouse',
      'EV charging & micromobility infrastructure',
      'Home automation features',
      'Bosch/Siemens kitchen appliances',
      'Duravit & Grohe bathrooms',
      'Marble flooring in living areas',
    ],
  },
  {
    id: '12',
    developerName: 'Sobha Realty',
    projectName: 'Sobha SkyParks',
    location: 'Sheikh Zayed Road, Business Bay, Dubai',
    startingPrice: 2_860_000,
    paymentPlan: '70/30 — 10% booking, 60% during construction, 30% on handover',
    handoverDate: 'December 2031',
    unitTypes: ['1BR', '2BR', '3BR', '4BR', 'Penthouse'],
    goldenVisaEligible: true,
    brochureUrl: null,
    roiEstimate: 8.0,
    status: 'Off-Plan',
    image: '/images/properties/sobha-skyparks-lounge.jpg',
    gallery: [
      '/images/properties/sobha-skyparks-lounge.jpg',
      '/images/properties/sobha-skyparks-pool.jpg',
      '/images/properties/sobha-skyparks-terrace.jpg',
      '/images/properties/sobha-skyparks-hero.jpg',
      '/images/properties/sobha-skyparks-garden.jpg',
    ],
    featured: true,
    beds: '1–4 + Duplex',
    sqft: '684 – 4,956 sq.ft.',
    description: 'Rising 450 metres above Sheikh Zayed Road, Sobha SkyParks is Dubai\'s most anticipated supertall residential landmark — 109 floors, 684 residences, and 4 immersive Sky-Parks spanning 24 levels. Located between Downtown Dubai and Business Bay with direct metro access. 1BR from AED 2.86M, 2BR from AED 4.75M, 3BR from AED 9.35M. Floor-to-ceiling glass throughout, sweeping views of the Burj Khalifa, Arabian Gulf and Dubai skyline from every level. Completion December 2031.',
    amenities: [
      'Infinity pool at 370m — Burj Khalifa & Gulf views',
      'Zone 1 Adventure SkyPark — kids splash, slides, padel, gaming',
      'Zone 2 Active Life SkyPark — skyline running track, yoga, calisthenics',
      'Zone 3 Lush Life SkyPark — zen gardens, glass pavilions, sensory path',
      'Zone 4 Luxe Life SkyPark — floating deck, private terraces, sunset dining',
      'Grand hotel-style lobby',
      'Floor-to-ceiling windows in all residences',
      'Private balconies — SZR, Gulf, Downtown & Canal views',
      'Fully fitted Bosch kitchen (fridge, oven, hob, dishwasher, washer-dryer)',
      'Duravit sanitary fixtures',
      'Smart home automation (temperature & lighting)',
      'High-performance double-glazed facade',
      '5 min to Business Bay · 10 min to DIFC · 13 min to Downtown',
      'Business Bay Metro Station — walking distance',
      'All units above AED 2M eligible for UAE 10-Year Golden Visa',
      'Projected 8–9% rental yield',
      '4–6% annual price appreciation forecast',
    ],
  },  {
    id: '13',
    developerName: 'Sobha Realty',
    projectName: 'Sobha Sanctuary',
    location: 'Dubailand, Al Ain Road, Dubai',
    startingPrice: 3_990_000,
    paymentPlan: '10/50/40 — 10% booking, 50% during construction, 40% on handover',
    handoverDate: 'Q3 2029',
    unitTypes: ['4BR', '5BR', '6BR', 'Villa', 'Townhouse'],
    goldenVisaEligible: true,
    brochureUrl: null,
    roiEstimate: 6.5,
    status: 'Off-Plan' as const,
    image: '/images/properties/sobha-sanctuary-hero.jpg',
    gallery: [
      '/images/properties/sobha-sanctuary-hero.jpg',
      '/images/properties/sobha-sanctuary-lagoon.jpg',
      '/images/properties/sobha-sanctuary-waterfall.jpg',
      '/images/properties/sobha-sanctuary-bedroom.jpg',
      '/images/properties/sobha-sanctuary-mall.jpg',
    ],
    videoUrl: 'https://www.youtube.com/embed/qalr65QxbI0',
    featured: true,
    beds: '4, 5 & 6',
    sqft: '2,459 – 7,191 sq.ft.',
    description: "Sobha Sanctuary is Sobha Realty's most ambitious masterplan — a AED 50 billion, 37.4 million sq.ft. wellness community in Dubailand designed for 20,000 families. Built around 6km of crystal lagoons, 50,000+ trees, and a 1 million sq.ft. central park, it features its own mall, two international schools, a hospital, and 22km of cycling tracks.",
    amenities: [
      '6km Crystal Lagoon with beach access',
      'Sobha Sanctuary Mall — retail & dining',
      'Two international schools on-site',
      'Community hospital',
      '1 million sq.ft. Central Park',
      '22km cycling tracks',
      '9km jogging & wellness loop',
      '50,000+ trees across the masterplan',
      'Padel courts & football grounds',
      'Skate park',
      'Yoga pavilions & meditation gardens',
      'State-of-the-art wellness centre',
      'Private boat rides & water plaza',
      'Resort-style swimming pools',
      'Pet-friendly walking routes',
    ],
  },
  {
    id: '14',
    developerName: 'Danube Properties',
    projectName: 'Greenz by Danube',
    location: 'Dubai Academic City, near Dubai Silicon Oasis',
    startingPrice: 2_500_000,
    paymentPlan: '1% monthly payment plan',
    handoverDate: 'December 2029',
    unitTypes: ['3BR', '4BR', '5BR', 'Townhouse', 'Villa'],
    goldenVisaEligible: true,
    brochureUrl: null,
    roiEstimate: 7.5,
    status: 'Off-Plan' as const,
    image: '/images/properties/greenz-front.jpg',
    gallery: [
      '/images/properties/greenz-front.jpg',
      '/images/properties/greenz-beachhub.jpg',
      '/images/properties/greenz-spa.jpg',
      '/images/properties/greenz-sanctuary.jpg',
      '/images/properties/greenz-wellness.jpg',
    ],
    videoUrl: 'https://www.youtube.com/embed/u7dexMTtfFY',
    featured: true,
    beds: '3, 4 & 5',
    sqft: 'Townhouses from ~2,500 sq.ft. | Twin Villas from ~4,000 sq.ft.',
    description: "Greenz by Danube is a master-planned resort community in Dubai Academic City — townhouses and twin villas surrounded by lush greenery, a musical dancing fountain, and 50+ world-class amenities across 20,000 sq.ft. of lifestyle space. Backed by Dubai's AED 12.8 billion Silicon Oasis tech-hub expansion (District 10 initiative), Greenz sits within one of Dubai's fastest-growing corridors — 5 min from Sheikh Mohammed bin Zayed Road, 18 min from Downtown Dubai. Fully furnished by Dolce Vita with Italian kitchen appliances, private elevators, floating staircases, and private sky gardens.",
    amenities: [
      'Musical Dancing Fountain — heart of the community',
      '3.75km circular jogging & cycling track',
      'Beach lagoon with sandy beach club & rooftop terrace',
      'Resort-style swimming pools & kids water park',
      '20,000 sq.ft. fitness & wellness centre',
      '2-floor panoramic gym with natural light',
      'Spa — steam, sauna, ice bath, infrared & cryotherapy',
      '10 dedicated sports courts (tennis, padel, football, cricket, basketball)',
      'Kids nursery, play zones, trampoline & wall climbing',
      'Indoor cinema, podcast room & business centre',
      'Family BBQ area & cabana seating',
      'Open yoga, meditation & Zumba platforms',
      'Giant musical piano walkway',
      'Mosque at community centre',
      '20,000 sq.ft. retail & dining promenade',
      'Electric golf cart transit & metro shuttle every 30 min',
      'Fully furnished by Dolce Vita (villas & townhouses)',
      'Private elevator inside every 4BR & 5BR home',
      'Private sky garden on roof floor',
      'Italian kitchen appliances & floating staircase',
      'Golden Visa eligible (all units above AED 2M)',
      '27 international universities within 5 minutes',
      '4-6% annual price appreciation forecast',
    ],
  },
  {
    id: '15',
    developerName: 'Imtiaz Developments',
    projectName: 'Cove Boulevard',
    location: 'Dubailand, Dubai',
    startingPrice: 750_000,
    paymentPlan: '60/40 (Option 1): 20% booking + 7 installments + 40% on completion (June 2028). Option 2 — 70/30 post-handover: 20% booking + 7 installments + 10% completion + 30% over 3 years at 2.5% quarterly',
    handoverDate: 'June 2028',
    unitTypes: ['Studio', '1BR', '2BR', '3BR'],
    goldenVisaEligible: 'check',
    brochureUrl: null,
    roiEstimate: 7.5,
    status: 'Off-Plan',
    image: '/images/properties/cove-boulevard-hero.jpg',
    gallery: [
      '/images/properties/cove-boulevard-hero.jpg',
      '/images/properties/cove-boulevard-terrace.jpg',
      '/images/properties/cove-boulevard-pool.jpg',
      '/images/properties/cove-boulevard-living.jpg',
      '/images/properties/cove-boulevard-bedroom.jpg',
    ],
    videoUrl: 'https://youtu.be/TlGtRx469-I',
    featured: false,
    beds: 'Studio – 3BR',
    description: 'Cove Boulevard by Imtiaz is a landmark mixed-use tower in Dubailand where work, lifestyle and residence converge under one roof. The 2B + G + 4P + 30 + Rooftop structure houses 436 units — 149 world-class offices (L1–L13) plus 172 studios, 62 one-bedroom, 48 two-bedroom and 5 three-bedroom residences (L15–L30). Two investor-friendly payment plans: 60/40 or 70/30 with 3-year post-handover option. Strategically positioned just 5 minutes from Dubai Outlet Mall, Academic City, Silicon Oasis and Global Village; 12 minutes from Desert Palm Polo Club and Meydan Racecourse; 20 minutes from Downtown Dubai, Burj Khalifa and Dubai International Airport.',
    amenities: [
      'Rooftop infinity pool with panoramic skyline views',
      'Family swimming pool',
      'Fully equipped gym',
      'Outdoor yoga retreat',
      'Elevated garden',
      'Kids play area',
      'Jacuzzi',
      'Clubhouse',
      'BBQ area',
      'Lush greenery throughout',
      'Grand entrance with Meet & Greet lounge',
      'Ample parking space',
      'World-class offices L1–L13: high-ceiling workspaces with ambient light',
      'Office gym, business lounge & dedicated parking',
      'Easy access to all major Dubai hubs',
      '5 mins — Dubai Outlet Mall, Academic City, Silicon Oasis, Global Village, IMG Worlds of Adventure',
      '12 mins — Desert Palm Polo Club, Dubai Safari Park, Meydan Racecourse',
      '20 mins — Dubai Intl. Airport, Downtown Dubai, Dubai Mall, Burj Khalifa',
      '25 mins — Dubai Marina, Palm Jumeirah, Expo City Dubai',
      'Two flexible payment plans: 60/40 or 70/30 post-handover (2.5% quarterly over 3 years)',
    ],
  },
  {
    id: '16',
    developerName: 'Imtiaz Developments',
    projectName: 'Cove Grand by Imtiaz',
    location: 'Dubailand, Dubai',
    startingPrice: 690_000,
    paymentPlan: 'Option 1 (50/50): 20% booking · 5% Sep 2025 · 5% Nov 2025 · 5% Mar 2026 · 5% Jun 2026 · 5% Oct 2026 · 5% Mar 2027 · 50% Dec 2027 on completion. Option 2 (Post-Handover): 20% booking · staged installments · 15% on completion · 30% over 3 years at 2.5% quarterly',
    handoverDate: 'December 2027',
    unitTypes: ['Studio', '1BR', '2BR', '3BR'],
    goldenVisaEligible: 'check',
    brochureUrl: null,
    roiEstimate: 7.8,
    status: 'Off-Plan',
    image: '/images/properties/cove-grand-hero.jpg',
    gallery: [
      '/images/properties/cove-grand-hero.jpg',
      '/images/properties/cove-grand-pool.jpg',
      '/images/properties/cove-grand-balconies.jpg',
      '/images/properties/cove-grand-living.jpg',
      '/images/properties/cove-grand-bedroom.jpg',
    ],
    featured: true,
    beds: 'Studio – 3BR',
    sqft: 'Studio from 386 sq.ft · 1BR from 707 sq.ft · 2BR from 1,282 sq.ft · 3BR from 1,627 sq.ft',
    description: 'Cove Grand by Imtiaz is an elegant residential sanctuary nestled beside a lush park in Dubailand — a vibrant, family-friendly community designed for those who seek more from everyday living. Rising as twin towers (1B + G + 3P + 17 + Rooftop), it features contemporary architecture, generously proportioned layouts and lifestyle-rich amenities including a rooftop infinity pool, open-air cinema and mini golf court. Fitted with premium Siemens appliances, VitrA bathrooms and Grohe fixtures throughout. Studios from AED 690K, 3BRs from AED 1.92M — with two flexible payment plans including a 3-year post-handover option. 5 minutes from IMG Worlds, Academic City, Silicon Oasis and Global Village; 20 minutes from Downtown Dubai and Burj Khalifa.',
    amenities: [
      'Infinity swimming pool',
      'Rooftop poolside cabana',
      'Rooftop sundeck',
      'Kids\' pool',
      'Poolside bar',
      'Fully equipped gym',
      'Modern clubhouse',
      'Open-air cinema',
      'Mini golf court',
      'BBQ area',
      'Running track',
      'Kids\' play area',
      'Outdoor seating areas',
      'Siemens kitchen appliances',
      'VitrA bathroom fittings',
      'Grohe fixtures throughout',
      'Amazon Alexa smart home integration',
      '5 min — IMG Worlds, Academic City, Silicon Oasis, Global Village, Dubai Outlet Mall',
      '12 min — Desert Palm Polo Club, Dubai Safari, Park Meydan Racecourse',
      '20 min — Dubai Intl. Airport, Downtown Dubai, Dubai Mall, Burj Khalifa',
      '25 min — Dubai Marina, Palm Jumeirah, Expo City Dubai',
    ],
  },
]

export const STATUS_COLORS: Record<Status, string> = {
  'Off-Plan': 'bg-blue-100 text-blue-800',
  'Ready': 'bg-green-100 text-green-800',
  'Secondary Market': 'bg-amber-100 text-amber-800',
}

export const AED_RATE: Record<string, number> = {
  AED: 1,
  INR: 22.8,
  USD: 0.272,
  GBP: 0.215,
  EUR: 0.251,
  SGD: 0.367,
}
